---

- hosts: localhost
  become: true
  vars:
          user: lucas
          kubectl_version: 1.16.0
          helm_version: 3.0.0
          docker_release: https://download.docker.com/linux/debian/dists/buster/pool/stable/amd64/docker-ce_18.09.8~3-0~debian-buster_amd64.deb 
          # Latest version of Docker supported by Minikube
  roles:
          - {role: 'common', tags: 'common'}
          - {role: 'reboot', tags: 'reboot'}
          - {role: 'vb', tags: 'vb'}
          - {role: 'kube', tags: 'kube'}
          - {role: 'tweak', tags: 'tweak'}
