---

- hosts: localhost
  become: true
  vars:
          user: lucas
          kubectl_version: 1.16.0
          helm_version: 3.0.0
          docker_release: https://download.docker.com/linux/fedora/29/x86_64/stable/Packages/docker-ce-18.09.9-3.fc29.x86_64.rpm 
          # Latest version of Docker supported by Minikube
  roles:
          - {role: 'common', tags: 'common'}
          - {role: 'reboot', tags: 'reboot'}
          - {role: 'vb', tags: 'vb'}
          - {role: 'kube', tags: 'kube'}
          - {role: 'tweak', tags: 'tweak'}
