  - name: "Add Docker dependencies"
    apt:
      state: present
      update_cache: true
      name: 
        ["python3-dev", "perl", "libnotify-dev", "lvm2", "python3-pip","apt-transport-https","ca-certificates","curl","gnupg-agent","software-properties-common"]


  - name: "Enable ssh service"
    become: true
    command:
            systemctl enable ssh.service

  - name: "Add docker repo key"
    become: true
    command:
      apt-key adv --fetch-keys https://download.docker.com/linux/debian/gpg
 
  - name: "add repo to sources.list"
    become: true
    command:
      add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
  
  - name: "wget dockers .deb pkg"
    get_url:
        url: "{{docker_release}}"
        dest: /tmp/docker.deb

  - name: install docker cli
    apt:
      name: ["docker-ce-cli"]
  
  - name: "Install Docker"
    apt:
      deb: /tmp/docker.deb

  - name: "Start and enable Docker"
    become: true
    command:

            systemctl start docker.service

  - name: "Enable docker.service"
    become: true
    command:

            systemctl enable docker.service

  - name: "Add me to Docker users"
    become: true
    command:
      usermod -aG docker {{user}}

  - name: "Install Docker-compose"
    become: true
    command:
      pip3 install docker-compose

