# This script installs Virtualbox on Fedora 31




  - name: "Wget virtualbox.repo"
    get_url:
            url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
            dest: /etc/yum.repos.d/

  - name: "Figure out kernel version"
    command:
            uname -r
    register: kernel_version

            
  - name: "Install Dependencies"
    dnf:
            name: ["binutils","gcc", "make", "patch", "libgomp", "glibc-headers", "glibc-devel", "kernel-headers", "kernel-devel-{{kernel_version.stdout}}", "dkms",                  "qt5-qtx11extras", "libxkbcommon"]
            state: present

  - name: "Install Virtual Box"
    dnf:
            name: ["VirtualBox-6.0"]
            state: present 

  - name: "Rebuild kernel modules"
    command:
            /usr/lib/virtualbox/vboxdrv.sh setup
      
  - name: "Add me to vbox users"
    command:
            usermod -aG vboxusers {{user}}



# https://www.if-not-true-then-false.com/2010/install-virtualbox-with-yum-on-fedora-centos-red-hat-rhel/
