# This script installs Virtualbox on Fedora 31




  - name: add vbox key
    command:
      apt-key adv --fetch-keys https://www.virtualbox.org/download/oracle_vbox_2016.asc    

  - name: "Figure out kernel version"
    command:
            uname -r
    register: kernel_version

            
  - name: "Install Dependencies"
    apt:
          name: ["binutils","gcc", "make", "patch","dkms"]
          state: present
  
  - name: add vbox repo
    command:
      add-apt-repository \
      "deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian buster contrib"

  - name: "Install Virtual Box"
    apt:
      update_cache: true
      name: ["virtualbox-6.0"]
      state: present 

#  - name: "Rebuild kernel modules"
 #   command:
  #          /usr/lib/virtualbox/vboxdrv.sh setup
      
  - name: "Add me to vbox users"
    command:
            usermod -aG vboxusers {{user}}

  - name: add opera key
    command:
      apt-key adv --fetch-keys https://deb.opera.com/archive.key

  - name: add opera repo
    command:
      add-apt-repository "deb [arch=i386,amd64] https://deb.opera.com/opera-stable/ stable non-free"

  - name: install opera
    apt:
      update_cache: true
      name: ["opera-stable"]
  
  - name: "wget awscli"
    get_url:
            url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
            dest: "/tmp/awscli.zip"
            group: "{{user}}"  
  
  - name: unzip awscli
    unarchive:
      src: "/tmp/awscli.zip"
      dest: "/tmp"
    
  - name: install awscli
    command:
      sh /tmp/aws/install
    ignore_errors: yes

  - name: dl azurecli
    get_url:
      url: https://aka.ms/InstallAzureCLIDeb
      dest: "/tmp/azurecli"
      group: "{{user}}"
      mode: "0744"

